import Link from "next/link";
import { notFound } from "next/navigation";
import { getFleetSnapshot } from "@/lib/fleet";

function bytes(value?: number) { if (value === undefined) return "Unknown"; return `${(value / 1024 / 1024 / 1024).toFixed(1)} GB`; }
function Obs({ name, state, label, detail }: { name: string; state: string; label: string; detail?: string }) { return <div className="detail-observation"><div><span className={`health-icon health-${state}`}><i className={`dot dot-${state}`} /></span><strong>{name}</strong></div><b>{label}</b><small>{detail || "No additional detail"}</small></div>; }

export default async function MachinePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const fleet = await getFleetSnapshot(); const machine = fleet.machines.find((item) => item.id === id); if (!machine) notFound();
  const { smb, forgegrid, meshcentral, action1 } = machine.observations;
  return <main><header className="topbar detail-top"><Link className="back-link" href="/">← Fleet</Link><div className="topbar-meta"><span className="live-pill"><i className="dot dot-online" />Live snapshot</span></div></header><section className="detail-hero"><div><p className="eyebrow">{machine.name} / machine detail</p><h1>{machine.hostname}</h1><p className="model-line">{machine.model} <span>•</span> {machine.mountPath}</p></div><div className={`state state-${machine.derived.state}`}><i className={`dot dot-${machine.derived.state}`} />{machine.derived.label}</div></section><nav className="detail-nav"><a href="#overview">Overview</a><a href="#integrations">Integrations</a><a href="#storage">Storage</a><a href="#activity">Activity</a></nav><section id="overview" className="detail-section"><div className="section-kicker"><span className="section-index">01</span><div><p className="eyebrow">Overview</p><h2>Current observations</h2></div></div><div className="detail-grid"><Obs name="SMB filesystem" state={smb.state} label={smb.label} detail={smb.detail} /><Obs name="MeshCentral" state={meshcentral.state} label={meshcentral.label} detail={meshcentral.detail} /><Obs name="ForgeGrid" state={forgegrid.state} label={forgegrid.label} detail={forgegrid.detail} /><Obs name="Action1" state={action1.state} label={action1.label} detail={action1.detail} /></div></section><section id="integrations" className="detail-section"><div className="section-kicker"><span className="section-index">02</span><div><p className="eyebrow">Delegated actions</p><h2>Use the system that owns it</h2></div></div><div className="action-row">{meshcentral.consoleUrl ? <a className="action-button primary" href={meshcentral.consoleUrl} target="_blank" rel="noreferrer">Open MeshCentral ↗</a> : <span className="action-button disabled">MeshCentral unavailable</span>}<a className="action-button" href={`file://${machine.mountPath}`}>Open Files ↗</a><span className="action-button disabled">Remote desktop delegated to MeshCentral</span></div></section><section id="storage" className="detail-section"><div className="section-kicker"><span className="section-index">03</span><div><p className="eyebrow">Storage</p><h2>Mounted filesystem</h2></div></div><div className="storage-panel"><div><span className="eyebrow">Free space</span><strong>{bytes(smb.freeBytes)}</strong></div><div><span className="eyebrow">Used</span><strong>{bytes(smb.usedBytes)}</strong></div><div><span className="eyebrow">Capacity</span><strong>{bytes(smb.totalBytes)}</strong></div></div></section><section id="activity" className="detail-section muted-section"><p className="eyebrow">Activity</p><p>Activity history will be added once an event source is configured. This V1 shows only observations from the current server-side snapshot.</p></section><footer><span>Observed {new Date(fleet.generatedAt).toLocaleString()}</span><Link href="/">Back to fleet</Link></footer></main>;
}
